import Head from 'next/head';
import Layout from '../components/Layout';
import { client } from '../lib/client';
import 'bootstrap/dist/css/bootstrap.min.css';
import Product from '../components/Product';
import { useEffect, useState } from 'react';

export default function Home({ parrilla }) {
  return (
    <Layout>
      <div>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}

        <main className="main">
          <nav id="sub-menu" className="subMenu">
            <a href="#1">Parrillas</a>
            <a href="#2">Platos</a>
            <a href="#3">Porciones</a>
            <a href="#4">Bebidas</a>
            <a href="#5">Postres</a>
            <span className="indicador" id="indicador"></span>
          </nav>
          <div className="container-main">
            <div className="seccion" id="1">
              <div className="cuadradro">
                <h1>Parrillas</h1>
              </div>
              {parrilla?.map((parrilla) => (
                <Product key={parrilla._id} parrilla={parrilla} />
              ))}
            </div>
            <div className="seccion" id="2">
              <div className="cuadradro">
                <h1>Platos</h1>
              </div>
              {parrilla?.map((parrilla) => (
                <Product key={parrilla._id} parrilla={parrilla} />
              ))}
            </div>
            <div className="seccion" id="3">
              <div className="cuadradro">
                <h1>Porciones</h1>
              </div>
              {parrilla?.map((parrilla) => (
                <Product key={parrilla._id} parrilla={parrilla} />
              ))}
            </div>
            <div className="seccion" id="4">
              <div className="cuadradro">
                <h1>Bebidas</h1>
              </div>
              {parrilla?.map((parrilla) => (
                <Product key={parrilla._id} parrilla={parrilla} />
              ))}
            </div>
            <div className="seccion" id="5">
              <div className="cuadradro">
                <h1>Postres</h1>
              </div>
              {parrilla?.map((parrilla) => (
                <Product key={parrilla._id} parrilla={parrilla} />
              ))}
            </div>
          </div>
        </main>
      </div>
    </Layout>
  );
}
export const getServerSideProps = async () => {
  const query = '*[_type == "parrilla"]';
  const parrilla = await client.fetch(query);
  return {
    props: {
      parrilla,
    },
  };
};
